### PR TITLE
Add scale factor setting

### PR DESCRIPTION
**Pull request by ghost**
Implementation copied from https://github.com/grafana/grafana-kiosk/pull/77

### CODE REVIEW

**Comment by briangann** [comment]
it will be merged, just need to test it out to verify it is working as intended

**Comment by schmidp** [comment]
I have checked out [nils-vixel:main](https://github.com/nils-vixel/grafana-kiosk/tree/main) on my Mac and ran `make -l` copied the `linux_armv7` to a RPi4:

no scale-factor on config:

missing

1.5:



2.0:

**Comment by briangann** [comment]
will need to redo this PR, the submitter has deleted their account before signing the CLA

**Comment by wizardofdevops** [comment]
https://github.com/grafana/grafana-kiosk/pull/120/files

I just opened another PR since our hero went AWOL.

**Comment by briangann** [comment]
Fixed by PR #120

**Pull request closed without merging**
