### PR TITLE
AzureAD Auto-Login Local Override

### PR DESCRIPTION
**Pull request by friedpope**
This is for Issue #106.  I think it's ready to merge, the changes are pretty simple.

### CODE REVIEW

**Comment by friedpope** [comment]
I'm not sure what that last codeclimate issue is on line 1, I'm happy to fix it if anyone can add some more detail as to what's wrong.

**Comment by briangann** [comment]
it's a "gofmt" issue, just formatting that can be fixed post-merge.

**Review by briangann — CHANGES_REQUESTED** [review]
are there docs to be added for this option?

**Comment by friedpope** [comment]
> are there docs to be added for this option?

Sure, I'll work on an update to README.md tomorrow.

**Comment by briangann** [comment]
can you run `mage build:format` to update the source files to pass the "gofmt" check?

**Review by briangann — APPROVED** [review]

**Pull request merged**
