### PR TITLE
Fix "choose your search engine" pop-up

### PR DESCRIPTION
**Pull request by LarsStegman**
Solves #137 

Solution by @mburghol

### CODE REVIEW

**Comment by S-Fitzy-Picnic** [comment]
Hi, what is the chance that this will be approved and committed to the prod build any time soon? We make use of this kiosk in a production environment and not having this resolution is hindering visibility in our workflow.

**Comment by LarsStegman** [comment]
@briangann

**Comment by briangann** [comment]
will test this out today and merge. thanks!

**Comment by jasase** [comment]
Hello, any news regarding this change and a possible release?

**Comment by Moritz-M** [comment]
@briangann do you know if there is any timeline on when this will be merged?

**Comment by LarsStegman** [comment]
Until it's merged, it's relatively easy to build it yourself!

`go build ./pkg/cmd/grafana-kiosk`

**Comment by briangann** [comment]
sorry for the delay, i haven't had a change to test it, but will be able to later today.

**Pull request merged**
